@api_host = http://localhost:3000
@admin_token = {{auth_flows.http.admin_token}}
@league_name = My Awesome League
@league_id =

### Create a New League (Admin)
POST {{api_host}}/api/league
Content-Type: application/json
Authorization: Bearer {{admin_token}}

{
  "name": "{{league_name}}"
}

@league_id = {{response.body.id}}

### Get League by ID (Admin)
GET {{api_host}}/api/league/{{league_id}}
Authorization: Bearer {{admin_token}}

### Delete League (Admin)
DELETE {{api_host}}/api/league/{{league_id}}
Authorization: Bearer {{admin_token}}
